# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Unit Test HueBoo."
  lane :test do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Send HueBoo to TestFlight."
  lane :testflight do
    match_with_options(type: "appstore")
    increment_build_number(build_number: Date.today.to_time.to_i)
    gym(
      output_directory: "testflight_build",
      export_method: "app-store"
    )
  end

  desc "Resolve Signing Certificates and Provisioning Profiles."
  lane :match_with_options do |options|
    matchType = options[:type]
    match(type: matchType)
  end

end
